### Endpoint de teste

GET http://localhost:3003/ping

### Endpoint de pesquisar produtos

GET http://localhost:3003/product

### Endpoint de pequisar produto pelo id
GET http://localhost:3003/product/8371

### Endpoint de pesquisar produto pela tag
GET http://localhost:3003/product/casual

### Endpoint de criar produto
POST http://localhost:3003/product
Content-Type: application/json

{
    "name": "CALÇA FUSEAU",
    "tags": ["casual", "liso"]
}